import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PlaylistContextProvider from "./contexts/PlaylistContext";
import { MySessionProvider } from "./hooks/SessionProvider";
import { SessionProvider } from "next-auth/react";
import SongContextProvider from "./contexts/SongContext";

// Load Google Inter font
const inter = Inter({ subsets: ["latin"] });

// Define metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <MySessionProvider>
          <PlaylistContextProvider>
            <SongContextProvider>{children}</SongContextProvider>
          </PlaylistContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
